from __future__ import annotations

import json
import os
from pathlib import Path
from urllib.error import URLError
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse
from urllib.request import urlopen

import uvicorn
from dotenv import load_dotenv


ROOT_DIR = Path(__file__).resolve().parent
ENV_PATH = ROOT_DIR / ".env"
FRONTEND_CONFIG_PATH = ROOT_DIR / "frontend" / "assets" / "config.js"


def _bool_env(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _is_local_url(url: str) -> bool:
    if not url:
        return True
    parsed = urlparse(url)
    host = (parsed.hostname or "").lower()
    return host in {"localhost", "127.0.0.1", "0.0.0.0", ""}


def _is_ngrok_url(url: str) -> bool:
    if not url:
        return False
    host = (urlparse(url).hostname or "").lower()
    return "ngrok" in host


def _origin(url: str) -> str:
    parsed = urlparse(url)
    if not parsed.scheme or not parsed.netloc:
        return ""
    return f"{parsed.scheme}://{parsed.netloc}"


def _ensure_api_base_in_url(webapp_url: str, api_base: str) -> str:
    if not webapp_url:
        return webapp_url
    parsed = urlparse(webapp_url)
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query.pop("auth_token", None)
    if api_base:
        query["api_base"] = api_base
    return urlunparse(
        (
            parsed.scheme,
            parsed.netloc,
            parsed.path,
            parsed.params,
            urlencode(query),
            parsed.fragment,
        )
    )


def _detect_ngrok_public_url() -> str:
    try:
        with urlopen("http://127.0.0.1:4040/api/tunnels", timeout=1.5) as response:
            data = json.loads(response.read().decode("utf-8"))
    except (URLError, TimeoutError, ValueError):
        return ""

    for tunnel in data.get("tunnels", []):
        public_url = str(tunnel.get("public_url", "")).strip()
        if public_url.startswith("https://"):
            return public_url
    return ""


def _write_frontend_config(api_base: str) -> None:
    content = (
        "window.APP_CONFIG = {\n"
        "  // Auto-generated by run.py\n"
        f"  API_BASE: \"{api_base}\"\n"
        "};\n"
    )
    FRONTEND_CONFIG_PATH.write_text(content, encoding="utf-8")


def _bootstrap_runtime_env() -> None:
    load_dotenv(ENV_PATH)

    webapp_url = (os.getenv("WEBAPP_URL") or "").strip()
    public_api_base = (os.getenv("PUBLIC_API_BASE") or "").strip()

    if _bool_env("AUTO_DETECT_NGROK", True) and (_is_local_url(webapp_url) or _is_ngrok_url(webapp_url)):
        ngrok_origin = _detect_ngrok_public_url()
        if ngrok_origin:
            webapp_url = f"{ngrok_origin}/index.html"
            os.environ["WEBAPP_URL"] = webapp_url
            public_api_base = ngrok_origin
            os.environ["PUBLIC_API_BASE"] = public_api_base
            print(f"[run.py] Detected ngrok URL: {ngrok_origin}")
        elif _is_ngrok_url(webapp_url):
            print("[run.py] WARNING: ngrok URL configured, but active ngrok tunnel not found on 127.0.0.1:4040")

    if not public_api_base:
        webapp_origin = _origin(webapp_url)
        if webapp_origin and "github.io" not in webapp_origin:
            public_api_base = webapp_origin
            os.environ["PUBLIC_API_BASE"] = public_api_base

    if webapp_url and public_api_base:
        webapp_url = _ensure_api_base_in_url(webapp_url, public_api_base)
        os.environ["WEBAPP_URL"] = webapp_url

    if _bool_env("AUTO_SYNC_FRONTEND_CONFIG", True):
        _write_frontend_config(public_api_base)
        print(f"[run.py] frontend/assets/config.js API_BASE = '{public_api_base}'")

    print(f"[run.py] WEBAPP_URL = '{os.getenv('WEBAPP_URL', '')}'")
    print(f"[run.py] PUBLIC_API_BASE = '{os.getenv('PUBLIC_API_BASE', '')}'")


if __name__ == "__main__":
    _bootstrap_runtime_env()
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=False, app_dir="backend")
